Repository status-im/StatusQ, pull requests merged in 2022-05, with the labels that each got.

#639 fix(StatusListPicker): Disabled uncheck option and reset searcher
  sandbox/pages/StatusListPickerPage.qml
  src/StatusQ/Components/StatusListPicker.qml
Labels: type: bugfix

#642 fix(StatusBaseInput): Implement cursor as per designs
  src/StatusQ/Controls/StatusBaseInput.qml
Labels: type: ui

#643 fix(StatusBaseInput): Fixed border color on active focus loss
  src/StatusQ/Controls/StatusBaseInput.qml
Labels: type: ui

#647 build: Added all qmls and assets to resources (fixes release build)
  sandbox/qml.qrc
  statusq.qrc
Labels: type: build

#652 fix(StatusBaseButton): After loading, button keeps loader width, so the button size is bigger
  src/StatusQ/Controls/StatusBaseButton.qml
Labels: type: bugfix

#693 feat(StatusCommunityCard): First component iteration
  doc/src/images/status_community_card.png
  sandbox/DemoApp.qml
  sandbox/demoapp/StatusAppCommunitiesPortalView.qml
  sandbox/demoapp/data/Models.qml
  sandbox/images/CryptoKitties.png
  sandbox/images/CryptoPunks.png
  sandbox/images/Dragonerum.png
  sandbox/images/FriendsBenefits.png
  sandbox/images/P2PCrypto.png
  sandbox/images/SNT.png
  sandbox/images/Socks.png
  sandbox/images/StatusPunks.png
  sandbox/images/logo-test-image.png
  sandbox/main.qml
  sandbox/pages/StatusCommunityCardPage.qml
  sandbox/qml.qrc
  src/StatusQ/Components/StatusCommunityCard.qml
  src/StatusQ/Components/qmldir
Labels: type: feature, module: components
